"""
src/cognitive/state.py
----------------------
Defines the shared GraphState TypedDict that flows through every node
of the TelcOS Lite LangGraph topology.

All fields are Optional so that partially-populated states are valid
during intermediate graph transitions.  Pydantic V2 is used for
field-level validation helpers; the TypedDict itself is consumed
directly by LangGraph's StateGraph.
"""

from __future__ import annotations

from typing import Any, Optional
from typing_extensions import TypedDict


class RawEvent(TypedDict, total=False):
    """Structured representation of an inbound telco event."""

    event_id: str
    """Unique identifier generated by the Kafka consumer."""

    source: str
    """Origin system (e.g. 'OSS', 'BSS', 'NMS', 'alarm_mgr')."""

    category: str
    """High-level classification (e.g. 'fault', 'performance', 'config')."""

    severity: str
    """Normalised severity: CRITICAL | MAJOR | MINOR | WARNING | INFO."""

    payload: dict[str, Any]
    """Raw event body exactly as received from the Kafka topic."""

    received_at: str
    """ISO-8601 UTC timestamp at which the event entered the framework."""


class RetrievedContext(TypedDict, total=False):
    """Contextual knowledge fetched from ChromaDB / RAG pipeline."""

    runbooks: list[dict[str, Any]]
    """Relevant runbook chunks ranked by embedding similarity."""

    topology: dict[str, Any]
    """Affected network segment topology snapshot."""

    historical_incidents: list[dict[str, Any]]
    """Past incidents with matching signatures and their resolutions."""

    retrieval_latency_ms: float
    """Wall-clock time (ms) spent in the retrieval step."""


class ProposedCommands(TypedDict, total=False):
    """CLI / NETCONF / RESTCONF commands produced by the Strategy node."""

    commands: list[str]
    """Ordered list of device commands to be executed."""

    target_devices: list[str]
    """Hostnames or management IPs of devices targeted by the commands."""

    rollback_commands: list[str]
    """Inverse commands to restore state if execution fails."""

    rationale: str
    """LLM-generated explanation of why these commands address the event."""


class SafetyEvaluation(TypedDict, total=False):
    """Deterministic safety-layer verdict (must never be probabilistic)."""

    verdict: str
    """Strict enum value: 'safe' | 'unsafe'."""

    violated_policies: list[str]
    """Policy identifiers that were breached (empty when verdict='safe')."""

    risk_score: int
    """Integer 0-100; ≥ threshold implies 'unsafe'."""

    evaluated_at: str
    """ISO-8601 UTC timestamp of the safety evaluation."""

    evaluator_version: str
    """Semver of the safety ruleset used, for audit traceability."""


class ExecutionOutput(TypedDict, total=False):
    """Results collected after device command execution via Netmiko."""

    device_responses: dict[str, str]
    """Mapping of device hostname → raw CLI output."""

    success: bool
    """True only when every command on every target succeeded."""

    failed_devices: list[str]
    """Devices on which at least one command returned an error."""

    execution_latency_ms: float
    """Total wall-clock time (ms) for the full execution round-trip."""

    rollback_triggered: bool
    """Whether the rollback sequence was initiated."""


class GraphState(TypedDict, total=False):
    """
    Canonical state envelope passed between all nodes in the
    TelcOS Lite LangGraph topology.

    Design invariants
    -----------------
    * All fields are Optional (``total=False``) – nodes must never assume
      upstream fields are populated; they must guard with ``state.get()``.
    * The ``safety_evaluation`` field is the *sole* routing discriminant
      at the SAFETY → {EXECUTE | BLOCKED} conditional edge.
    * No business logic lives here – this is a pure data-carrier.
    """

    # ------------------------------------------------------------------ #
    # Ingress                                                              #
    # ------------------------------------------------------------------ #
    raw_event: Optional[RawEvent]
    """Normalised inbound event from the Kafka consumer."""

    # ------------------------------------------------------------------ #
    # Retrieval                                                            #
    # ------------------------------------------------------------------ #
    retrieved_context: Optional[RetrievedContext]
    """RAG-augmented knowledge retrieved by the TRIAGE node."""

    # ------------------------------------------------------------------ #
    # Planning                                                             #
    # ------------------------------------------------------------------ #
    proposed_commands: Optional[ProposedCommands]
    """Remediation plan produced by the STRATEGY node."""

    # ------------------------------------------------------------------ #
    # Safety gate                                                          #
    # ------------------------------------------------------------------ #
    safety_evaluation: Optional[SafetyEvaluation]
    """Deterministic verdict from the SAFETY node; drives conditional routing."""

    # ------------------------------------------------------------------ #
    # Execution                                                            #
    # ------------------------------------------------------------------ #
    execution_output: Optional[ExecutionOutput]
    """Collected device responses from the EXECUTE node."""

    # ------------------------------------------------------------------ #
    # Ticketing                                                            #
    # ------------------------------------------------------------------ #
    tmf_ticket_id: Optional[str]
    """TM Forum TMF621 trouble-ticket ID created by the TMF621 node."""